security:
  oauth2:
    client:
      clientId: tiy
      clientSecret: exquisite-dead-guy
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
  sessions: if-required
  user:
    password: password
server:
  port: 9999
  contextPath: /auth
